version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gha:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directories:
      - /
      - build
    allow:
      - dependency-type: all
    schedule:
      interval: weekly
    groups:
      go:
        patterns:
          - "*"
