name: CI
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - ubuntu-22.04
          - windows-2022
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.work
          cache-dependency-path: "**/go.sum"

      - name: run lint
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run ./build lint

      - name: run tests
        run: go run ./build test

      - name: build snapshot
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run ./build snapshot
