name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: curioswitch/go-build/.github/actions/setup-go@8cee71a440fb70ec08525081efdf8088d2b3618e # v0.8.3

      - name: run lints
        if: startsWith(matrix.os, 'ubuntu-')
        run: go run ./build lint

      - name: run tests
        run: go run ./build test
