name: Refresh Go Cache

on:
  push:
    branches:
      - main
    paths:
      - "**/go.mod"
      - "**/versions.go"
      - .github/workflows/refresh-go-cache.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  refresh:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    uses: curioswitch/go-build/.github/workflows/export-refresh-go-cache.yaml@b4bb86391b1e39db0dd8cad98e4d8be49c298077 # v0.6.1
    with:
      runner: ${{ matrix.os }}
