name: Refresh Go Cache

on:
  push:
    branches:
      - main
    paths:
      - "**/go.mod"
      - "**/versions.go"
      - .github/workflows/refresh-go-cache.yaml
  workflow_dispatch:

jobs:
  refresh:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    uses: curioswitch/go-build/.github/workflows/export-refresh-go-cache.yaml@7489f72867246693fc1cc65560c68cdc860a1f8a # v0.5.2
    with:
      runner: ${{ matrix.os }}
